// Mock data for development - will be replaced with Supabase data

import { Service, Staff, Appointment } from './types';

export const mockServices: Service[] = [
    {
        id: '1',
        name: 'Classic Haircut',
        description: 'Professional haircut with styling',
        category: 'men',
        duration_minutes: 30,
        price: 200,
        image_url: null,
        is_active: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '2',
        name: 'Ladies Haircut',
        description: 'Precision cut and blow dry',
        category: 'women',
        duration_minutes: 45,
        price: 400,
        image_url: null,
        is_active: true,
        sort_order: 2,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '3',
        name: 'Kids Haircut',
        description: 'Fun and gentle hair cutting for kids',
        category: 'unisex',
        duration_minutes: 20,
        price: 150,
        image_url: null,
        is_active: true,
        sort_order: 3,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '4',
        name: 'Beard Styling',
        description: 'Trim, shape, and style your beard',
        category: 'men',
        duration_minutes: 20,
        price: 150,
        image_url: null,
        is_active: true,
        sort_order: 4,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '5',
        name: 'Hair Spa',
        description: 'Relaxing spa treatment for healthy hair',
        category: 'unisex',
        duration_minutes: 60,
        price: 800,
        image_url: null,
        is_active: true,
        sort_order: 5,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '6',
        name: 'Hair Coloring',
        description: 'Professional color with premium products',
        category: 'unisex',
        duration_minutes: 90,
        price: 1500,
        image_url: null,
        is_active: true,
        sort_order: 6,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '7',
        name: 'Facial & Cleanup',
        description: 'Deep cleansing facial for glowing skin',
        category: 'unisex',
        duration_minutes: 45,
        price: 500,
        image_url: null,
        is_active: true,
        sort_order: 7,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '8',
        name: 'Bridal Makeup',
        description: 'Complete bridal makeup package',
        category: 'women',
        duration_minutes: 120,
        price: 5000,
        image_url: null,
        is_active: true,
        sort_order: 8,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '9',
        name: 'Keratin Treatment',
        description: 'Premium keratin smoothening',
        category: 'unisex',
        duration_minutes: 180,
        price: 4000,
        image_url: null,
        is_active: true,
        sort_order: 9,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
    {
        id: '10',
        name: 'Party Makeup',
        description: 'Glamorous makeup for special occasions',
        category: 'women',
        duration_minutes: 60,
        price: 2000,
        image_url: null,
        is_active: true,
        sort_order: 10,
        created_at: new Date().toISOString(),
        is_combo: false,
        is_featured: false,
    },
];

export const mockStaff: Staff[] = [
    {
        id: '1',
        name: 'Rahul Kumar',
        role: 'Senior Stylist',
        avatar_url: null,
        working_hours: {
            monday: { start: '09:00', end: '21:00', isOff: false },
            tuesday: { start: '09:00', end: '21:00', isOff: false },
            wednesday: { start: '09:00', end: '21:00', isOff: false },
            thursday: { start: '09:00', end: '21:00', isOff: false },
            friday: { start: '09:00', end: '21:00', isOff: false },
            saturday: { start: '09:00', end: '21:00', isOff: false },
            sunday: { start: '10:00', end: '18:00', isOff: false },
        },
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Priya Sharma',
        role: 'Beauty Expert',
        avatar_url: null,
        working_hours: {
            monday: { start: '09:00', end: '21:00', isOff: false },
            tuesday: { start: '09:00', end: '21:00', isOff: true },
            wednesday: { start: '09:00', end: '21:00', isOff: false },
            thursday: { start: '09:00', end: '21:00', isOff: false },
            friday: { start: '09:00', end: '21:00', isOff: false },
            saturday: { start: '09:00', end: '21:00', isOff: false },
            sunday: { start: '10:00', end: '18:00', isOff: false },
        },
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Amit Verma',
        role: 'Hair Specialist',
        avatar_url: null,
        working_hours: {
            monday: { start: '09:00', end: '21:00', isOff: false },
            tuesday: { start: '09:00', end: '21:00', isOff: false },
            wednesday: { start: '09:00', end: '21:00', isOff: true },
            thursday: { start: '09:00', end: '21:00', isOff: false },
            friday: { start: '09:00', end: '21:00', isOff: false },
            saturday: { start: '09:00', end: '21:00', isOff: false },
            sunday: { start: '10:00', end: '18:00', isOff: false },
        },
        is_active: true,
        created_at: new Date().toISOString(),
    },
];

export const mockAppointments: Appointment[] = [
    {
        id: '1',
        user_id: 'user1',
        service_id: '1',
        staff_id: '1',
        appointment_date: new Date().toISOString().split('T')[0],
        start_time: '10:00',
        end_time: '10:30',
        status: 'confirmed',
        notes: null,
        final_amount: null,
        payment_mode: null,
        created_at: new Date().toISOString(),
        discount_percent: null,
    },
    {
        id: '2',
        user_id: 'user1',
        service_id: '5',
        staff_id: '2',
        appointment_date: new Date().toISOString().split('T')[0],
        start_time: '14:00',
        end_time: '15:00',
        status: 'pending',
        notes: null,
        final_amount: null,
        payment_mode: null,
        created_at: new Date().toISOString(),
        discount_percent: null,
    },
];
